tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y openjdk-11-jdk
      wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
      unzip commandlinetools-linux-6858069_latest.zip -d cmdline-tools
      mkdir -p $ANDROID_HOME/cmdline-tools/latest
      mv cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest/
      yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
      $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
  - command: |
      ./gradlew build
